version: '2'
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:9000
    environment:
      - TZ=Europe/Madrid
      - CLOUDINARY_URL=cloudinary://131131783311296:hYbwcfxv1reh3k8tn84OwcaqjCM@boda
    links:
      - db
    ports:
      - $EXPOSE_IP:11080:9000
    volumes:
      - .:/opt/:rw
      - /opt/static
    networks:
      - db-net
      - service-grp-net

  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=db_pwd
      - POSTGRES_USER=db_user
      - POSTGRES_DB=db_db
    volumes:
      - db-data:/var/lib/postgres/data
    networks:
      - db-net

networks:
  db-net: {}
  service-grp-net:
    external: true

volumes:
  db-data: {}
